# Generated by Django 3.1.2 on 2021-12-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseGramatical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=200)),
                ('traducao', models.CharField(max_length=200)),
                ('definicao', models.TextField(help_text='Insira uma definição em português do termo.')),
                ('categoria', models.CharField(max_length=100)),
                ('equivalencia', models.IntegerField()),
                ('classe_gramatical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dicionario.classegramatical')),
            ],
        ),
    ]
