# Generated by Django 3.1.2 on 2021-12-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
