# Generated by Django 3.1.2 on 2021-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0002_termo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
