# Generated by Django 3.1.2 on 2021-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0003_auto_20211210_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='termo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='termo',
            name='categoria',
            field=models.ManyToManyField(to='dicionario.Categoria'),
        ),
    ]
