# Generated by Django 3.1.2 on 2021-12-13 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0004_auto_20211211_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='grafia_aportuguesada',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='termo',
            name='equivalencia',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
