# Generated by Django 3.1.2 on 2021-12-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0005_auto_20211213_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='grafia_aportuguesada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
