# Generated by Django 3.1.2 on 2021-12-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0006_auto_20211213_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=[], unique=True),
            preserve_default=False,
        ),
    ]
