# Generated by Django 3.1.2 on 2021-12-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0010_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
